### ISSUE TITLE
fix up getParam error messages

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#194]
Some issues:

Case 1: non-existent parameter name does not give useful error message:

> code <- nimbleCode({
> -     y ~ dnorm(mu, 1)
> -     mu ~ dnorm(0,2)
> - })
> 
> m <- nimbleModel(code, data = list(y=1), inits = list(mu = 0))
> defining model...
> building model...
> setting data and initial values...
> checking model sizes and dimensions...
> model building finished.
>  m$getParam('mu','sd')
> [1] 0.7071068
>  m$getParam('mu','prec')
> Error in makeParamInfo(model, node, param) : 
>   cannot have multiple nodes accessed by the same getParam if they have different types or dimensions for the same parameter.

Case 2: attempt to get params for multiple nodes gives half-result with non-useful warning:

> m$getParam(c('mu','y'), 'tau')
> [1] 2
> Warning message:
> In IDoptions == paramID :
>   longer object length is not a multiple of shorter object length

Case 3: attempt to get multiple params gives incorrect error message:

> m$getParam(c('mu'), c('mean','tau'))
> Error in makeParamInfo(model, node, param) : 
>   cannot have multiple nodes accessed by the same getParam if they have different types or dimensions for the same parameter.

**Comment by perrydv** [comment]
I’ll try to address case 1.

Obtaining multiple parameters for one node or the same param for multiple nodes in one call to getParams was not intended to work and not documented anywhere.  It would raise issues similar to values(): what is the desired behavior if one param is a matrix and the next a vector, or one asks for a matrix parameter from multiple nodes that may be different sizes in each node?  For values() we defined flattening behavior, but I’m not sure for getParam that would give the desired behavior, because I think it’s useful to preserve size and dimensions of a single parameter at a time so that model$getParam can be used within other expressions.

What does now work on devel from newNodeFxns that hasn’t been in a previous release is model$getParam(nodes[i], param), and similar for model$calculate(nodes[i]), etc.  That is, scalar indexing in a vector of node names is supported in the model operation functions.

**Comment by paciorek** [comment]
Yeah, the point of the issue was that the error messages are not good, not
that we want multi-param or multi-node functionality.  I just tried those
because I was confused by the error message for getParam(node,
non_existent_param) and was playing around to see what error messages
different things give.

I've started to work on enabling getParam for compiled models, as an FYI.

**Comment by perrydv** [comment]
done

**Comment by paciorek** [comment]
I'm still seeing inscrutable error messages if one tries to get a non-existent parameter on devel. But from this issue thread, I thought Perry addressed this... Thoughts?  I'm happy to address it.

code = nimbleCode({
     y ~ dbin(p,10)
     p ~ dbeta(mean = 0.5, sd = 0.25)
 })
 m = nimbleModel(code, data = list(y = 3), inits = list(p = .2))
 m$getParam('y','mean')

Error in makeParamInfo(model, node, param) : 
  cannot have an indexed vector of nodes used in getParam if they have different types or dimensions for the same parameter.

**Comment by paciorek** [comment]
Turns out I fixed this without realizing it by reworking how we get distribution info.  makeParamInfo now calls getParamID and that returns an interpretable error when an unknown parameter name is given. Before we were going directly into the distribution class and so the error was caught by native R functions rather than by a function within NIMBLE.
